const ON_TIME_CHANGE = "ON_TIME_CHANGE"
const FETCH_WEATHER_PENDING = 'FETCH_WEATHER_PENDING'
const FETCH_WEATHER_SUCCESS = 'FETCH_WEATHER_SUCCESS'
const FETCH_WEATHER_ERROR = 'FETCH_WEATHER_ERROR'

const FETCH_EXCHANGE_PENDING = 'FETCH_EXCHANGE_PENDING'
const FETCH_EXCHANGE_SUCCESS = 'FETCH_EXCHANGE_SUCCESS'
const FETCH_EXCHANGE_ERROR = 'FETCH_EXCHANGE_ERROR'

export {
    ON_TIME_CHANGE, FETCH_WEATHER_PENDING, FETCH_WEATHER_SUCCESS, FETCH_WEATHER_ERROR, FETCH_EXCHANGE_PENDING, FETCH_EXCHANGE_SUCCESS,FETCH_EXCHANGE_ERROR 
}